### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by vroddon** [oeg-upm/ORSD-template#1]
Congrats for this work!
Just wanted to say that this is an excellent resource.

But this link is broken in this sentence:
"This file contains a LaTeX template for defining the Ontology Requirements Specification (ORSD) file, as specified by the NeOn Methodology"
http://neon-project.org/web-content/media/book-chapters/Chapter-05.pdf

**Comment by mariapoveda** [comment]
Thanks @vroddon ! 

Maybe we can close or delete this repository as we are moving resources to https://github.com/oeg-upm/LOT-resources/tree/master/ORSD

What do you think @ocorcho ?

**Comment by ocorcho** [comment]
I agree on closing
